#!/usr/bin/env python3
"""Builds DaysUntil/Resources/Emoji.tsv, the emoji the icon picker offers, and beside it a file of
their names in each of the app's other languages, such as Emoji-ja.tsv.

The list is Unicode's emoji-test.txt, in its order, regrouped into the categories of Apple's
emoji picker, with each emoji's CLDR English name and keywords for search. Skin tone variants
and components are left out. Emoji the Mac can't draw yet are dropped by the app at run time,
so the list can run ahead of macOS. The other languages' files hold CLDR's names and keywords in
that language, for the emoji CLDR has them for.

Usage: scripts/make-emoji-list.py [emoji-test.txt cldr-json]
Without arguments it downloads the latest files from unicode.org and the CLDR JSON repository.
With them, cldr-json is a copy of that repository's cldr-json folder.
"""

import json
import pathlib
import sys
import urllib.request

EMOJI_TEST = "https://unicode.org/Public/emoji/latest/emoji-test.txt"
CLDR = "https://raw.githubusercontent.com/unicode-org/cldr-json/main/cldr-json"
LICENSE = "https://www.unicode.org/license.txt"
RESOURCES = pathlib.Path(__file__).resolve().parent.parent / "DaysUntil" / "Resources"

# The app's other languages, by their names in the app, and CLDR's locale for each.
LANGUAGES = {
    "ja": ("ja", "Japanese"),
    "ko": ("ko", "Korean"),
    "zh-Hans": ("zh", "Simplified Chinese"),
    "zh-Hant": ("zh-Hant", "Traditional Chinese"),
}

# Unicode's groups, in Apple's picker's categories and order. Components are left out.
CATEGORIES = {
    "Smileys & Emotion": "smileys",
    "People & Body": "smileys",
    "Animals & Nature": "animals",
    "Food & Drink": "food",
    "Activities": "activity",
    "Travel & Places": "travel",
    "Objects": "objects",
    "Symbols": "symbols",
    "Flags": "flags",
}
ORDER = ["smileys", "animals", "food", "activity", "travel", "objects", "symbols", "flags"]
SKIN_TONES = {chr(c) for c in range(0x1F3FB, 0x1F400)}


def read(source):
    if source.startswith("https://"):
        with urllib.request.urlopen(source) as response:
            return response.read().decode("utf-8")
    return pathlib.Path(source).read_text(encoding="utf-8")


def annotations(cldr, locale):
    """CLDR's names and keywords in `locale`, for single emoji and for sequences, by emoji."""
    entries = {}
    for package, key in (("cldr-annotations-full", "annotations"), ("cldr-annotations-derived-full", "annotationsDerived")):
        data = json.loads(read(f"{cldr}/{package}/{key}/{locale}/annotations.json"))
        entries.update(data[key]["annotations"])
    return entries


def lookup(entries, emoji):
    return entries.get(emoji) or entries.get(emoji.replace("️", "")) or {}


def extra_keywords(entry, name):
    """The keywords not already words of the name."""
    name_words = set(name.lower().replace(":", " ").replace("：", " ").split())
    words = [w.lower() for w in entry.get("default", []) if w.lower() not in name_words]
    return "|".join(dict.fromkeys(words))


def write(path, header, rows, license_text):
    lines = header + ["#"] + [f"# {line}".rstrip() for line in license_text.strip().splitlines()] + rows
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(rows)} emoji to {path}")


def main():
    test_source, cldr = sys.argv[1:] or [EMOJI_TEST, CLDR]
    test = read(test_source)
    english = annotations(cldr, "en")

    version = next(line.split(":", 1)[1].strip() for line in test.splitlines() if line.startswith("# Version:"))
    rows = {category: [] for category in ORDER}
    group = None
    for line in test.splitlines():
        if line.startswith("# group:"):
            group = line.split(":", 1)[1].strip()
            continue
        if "; fully-qualified" not in line or group not in CATEGORIES:
            continue
        # "1F3E0 ; fully-qualified # 🏠 E0.6 house"
        emoji, _, name = line.split("#", 1)[1].strip().split(" ", 2)
        if SKIN_TONES & set(emoji):
            continue
        rows[CATEGORIES[group]].append((emoji, name))
    emoji_list = [row for category in ORDER for row in rows[category]]
    category = {emoji: c for c in ORDER for emoji, _ in rows[c]}

    license_text = read(LICENSE)
    write(RESOURCES / "Emoji.tsv", [
        f"# The emoji the icon picker offers. Generated by scripts/make-emoji-list.py from Unicode's",
        f"# emoji-test.txt (Emoji {version}) and CLDR's English annotations. Do not edit by hand.",
        "# Columns: category, emoji, name, keywords separated by |.",
    ], [
        f"{category[emoji]}\t{emoji}\t{name}\t{extra_keywords(lookup(english, emoji), name)}"
        for emoji, name in emoji_list
    ], license_text)

    for language, (locale, title) in LANGUAGES.items():
        entries = annotations(cldr, locale)
        named = [(emoji, lookup(entries, emoji)) for emoji, _ in emoji_list]
        write(RESOURCES / f"Emoji-{language}.tsv", [
            f"# {title} names for the emoji in Emoji.tsv. Generated by scripts/make-emoji-list.py from",
            f"# CLDR's {locale} annotations. Do not edit by hand.",
            "# Columns: emoji, name, keywords separated by |.",
        ], [
            f"{emoji}\t{entry['tts'][0]}\t{extra_keywords(entry, entry['tts'][0])}"
            for emoji, entry in named if entry.get("tts")
        ], license_text)


if __name__ == "__main__":
    main()
