#!/usr/bin/env python3
"""Builds DaysUntil/Resources/Emoji.tsv, the emoji the icon picker offers.

The list is Unicode's emoji-test.txt, in its order, regrouped into the categories of Apple's
emoji picker, with each emoji's CLDR English name and keywords for search. Skin tone variants
and components are left out. Emoji the Mac can't draw yet are dropped by the app at run time,
so the list can run ahead of macOS.

Usage: scripts/make-emoji-list.py [emoji-test.txt annotations.json annotationsDerived.json]
Without arguments it downloads the latest files from unicode.org and the CLDR JSON repository.
"""

import json
import pathlib
import sys
import urllib.request

EMOJI_TEST = "https://unicode.org/Public/emoji/latest/emoji-test.txt"
CLDR = "https://raw.githubusercontent.com/unicode-org/cldr-json/main/cldr-json"
ANNOTATIONS = f"{CLDR}/cldr-annotations-full/annotations/en/annotations.json"
DERIVED = f"{CLDR}/cldr-annotations-derived-full/annotationsDerived/en/annotations.json"
LICENSE = "https://www.unicode.org/license.txt"
OUTPUT = pathlib.Path(__file__).resolve().parent.parent / "DaysUntil" / "Resources" / "Emoji.tsv"

# Unicode's groups, in Apple's picker's categories and order. Components are left out.
CATEGORIES = {
    "Smileys & Emotion": "smileys",
    "People & Body": "smileys",
    "Animals & Nature": "animals",
    "Food & Drink": "food",
    "Activities": "activity",
    "Travel & Places": "travel",
    "Objects": "objects",
    "Symbols": "symbols",
    "Flags": "flags",
}
ORDER = ["smileys", "animals", "food", "activity", "travel", "objects", "symbols", "flags"]
SKIN_TONES = {chr(c) for c in range(0x1F3FB, 0x1F400)}


def read(source):
    if source.startswith("https://"):
        with urllib.request.urlopen(source) as response:
            return response.read().decode("utf-8")
    return pathlib.Path(source).read_text(encoding="utf-8")


def main():
    sources = sys.argv[1:] or [EMOJI_TEST, ANNOTATIONS, DERIVED]
    test, annotations, derived = (read(s) for s in sources)
    keywords = {}
    for data, key in ((json.loads(annotations), "annotations"), (json.loads(derived), "annotationsDerived")):
        for emoji, entry in data[key]["annotations"].items():
            keywords[emoji] = entry.get("default", [])

    version = next(line.split(":", 1)[1].strip() for line in test.splitlines() if line.startswith("# Version:"))
    rows = {category: [] for category in ORDER}
    group = None
    for line in test.splitlines():
        if line.startswith("# group:"):
            group = line.split(":", 1)[1].strip()
            continue
        if "; fully-qualified" not in line or group not in CATEGORIES:
            continue
        # "1F3E0 ; fully-qualified # 🏠 E0.6 house"
        emoji, _, name = line.split("#", 1)[1].strip().split(" ", 2)
        if SKIN_TONES & set(emoji):
            continue
        words = keywords.get(emoji) or keywords.get(emoji.replace("️", "")) or []
        name_words = set(name.lower().replace(":", " ").split())
        extra = [w.lower() for w in words if w.lower() not in name_words]
        rows[CATEGORIES[group]].append(f"{CATEGORIES[group]}\t{emoji}\t{name}\t{'|'.join(dict.fromkeys(extra))}")

    license_text = read(LICENSE)
    header = [
        f"# The emoji the icon picker offers. Generated by scripts/make-emoji-list.py from Unicode's",
        f"# emoji-test.txt (Emoji {version}) and CLDR's English annotations. Do not edit by hand.",
        "# Columns: category, emoji, name, keywords separated by |.",
        "#",
    ] + [f"# {line}".rstrip() for line in license_text.strip().splitlines()]
    body = [row for category in ORDER for row in rows[category]]
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(header + body) + "\n", encoding="utf-8")
    print(f"Wrote {len(body)} emoji to {OUTPUT}")


if __name__ == "__main__":
    main()
